import type { Spec } from '@json-render/core'

const delivery = (id: string, status: 'Booking Confirmed' | 'In Transit' | 'Arrived at Port' | 'Customs' | 'Delivered', transportType: 'Sea' | 'Land' = 'Sea') => ({
  id, from: 'Shanghai', to: 'Cartagena', transportType, status, createdAt: '2026-08-29T10:30:00Z', deliveryTime: status === 'Delivered' ? 'Delivered' : '18 days',
})

export const catalogShowcase: Array<{ name: string; description: string; spec: Spec }> = [
  { name: 'AssistantMessage', description: 'Mensajes conversacionales con contenido anidado.', spec: { root: 'assistant', elements: { assistant: { type: 'AssistantMessage', props: { text: 'He encontrado tres envíos que necesitan atención.' }, children: [] } } } },
  ...(['Booking Confirmed', 'In Transit', 'Arrived at Port', 'Customs', 'Delivered'] as const).map((status) => ({ name: `ContainerProgress · ${status}`, description: 'Todas las etapas posibles del progreso de un contenedor.', spec: { root: `progress-${status}`, elements: { [`progress-${status}`]: { type: 'ContainerProgress', props: { currentStatus: status }, children: [] } } } })),
  ...(['Sea', 'Land'] as const).map((transportType) => ({ name: `DeliveryCard · ${transportType}`, description: 'Variantes de transporte marítimo y terrestre.', spec: { root: `delivery-${transportType}`, elements: { [`delivery-${transportType}`]: { type: 'DeliveryCard', props: delivery(`SHIP-${transportType}`, 'In Transit', transportType), children: [] } } } })),
  { name: 'DeliveryIssueCard', description: 'Tarjeta de entrega con incidencia operativa.', spec: { root: 'issue', elements: { issue: { type: 'DeliveryIssueCard', props: { ...delivery('SHIP-ISSUE', 'Customs'), issue: 'Customs clearance delayed' }, children: [] } } } },
  { name: 'ShipmentDocumentsTimeline', description: 'Estados completed, in_progress, pending y missing.', spec: { root: 'documents', elements: { documents: { type: 'ShipmentDocumentsTimeline', props: { title: 'Shipment documents', subtitle: 'Document readiness by milestone', documents: [
    { id: 'purchase-order', title: 'Purchase order', description: 'Commercial order approved.', status: 'completed', date: 'Aug 21, 2026' },
    { id: 'booking-confirmation', title: 'Booking confirmation', description: 'Carrier space is confirmed.', status: 'in_progress', date: 'Aug 24, 2026' },
    { id: 'bill-of-lading', title: 'Bill of lading', description: 'Awaiting carrier upload.', status: 'pending' },
    { id: 'invoice', title: 'Commercial invoice', description: 'Required before customs review.', status: 'missing' },
  ] }, children: [] } } } },
  ...([['line', 'Gráficos de línea'], ['pie', 'Gráficos circulares'], ['scatter', 'Gráficos de dispersión'], ['stackedArea', 'Gráficos de áreas apiladas'], ['fluctuation', 'Gráficos de fluctuaciones'], ['spider', 'Gráficos de araña'], ['groupedBar', 'Gráficos de barras agrupadas'], ['pyramid', 'Gráficos de pirámide'], ['frequencyPolygon', 'Polígonos de frecuencia']] as const).map(([chartType, name], index) => ({ name, description: 'Diagrama estadístico registrado como componente JSON Render.', spec: { root: `catalog-chart-${index}`, elements: { [`catalog-chart-${index}`]: { type: 'CatalogChart', props: { title: name, description: 'Variante interactiva del catálogo', chartType, data: chartType === 'scatter' ? [{ label: 'A', x: 12, y: 24 }, { label: 'B', x: 25, y: 18 }, { label: 'C', x: 38, y: 42 }, { label: 'D', x: 52, y: 34 }, { label: 'E', x: 68, y: 58 }] : chartType === 'pie' ? [{ label: 'Entregados', value: 46 }, { label: 'En tránsito', value: 31 }, { label: 'Aduana', value: 14 }, { label: 'Retrasados', value: 9 }] : chartType === 'spider' ? [{ label: 'Velocidad', value: 82 }, { label: 'Coste', value: 68 }, { label: 'Calidad', value: 91 }, { label: 'Cobertura', value: 74 }, { label: 'Riesgo', value: 60 }] : [{ label: 'Lun', value: 24, value2: 15 }, { label: 'Mar', value: 38, value2: 22 }, { label: 'Mié', value: 31, value2: 28 }, { label: 'Jue', value: 46, value2: 25 }, { label: 'Vie', value: 42, value2: 34 }], height: 260, showGrid: true }, children: [] } } } })),
  ...([['vertical', true, true], ['horizontal', true, false], ['vertical', false, true], ['horizontal', false, false]] as const).map(([orientation, showValues, showGrid], index) => ({ name: `BarChart · ${orientation} · ${showValues ? 'values' : 'clean'}`, description: 'Variantes de orientación, valores y cuadrícula.', spec: { root: `chart-${index}`, elements: { [`chart-${index}`]: { type: 'BarChart', props: { title: 'Shipments by status', description: 'Current shipment distribution', data: [{ label: 'Delivered', value: 42 }, { label: 'In transit', value: 28 }, { label: 'Customs', value: 9 }, { label: 'Delayed', value: 6 }], orientation, showValues, showGrid, height: orientation === 'horizontal' ? 260 : 300 }, children: [] } } } })),
]
