import type { Spec } from '@json-render/core'

const delivery = (id: string, status: 'Booking Confirmed' | 'In Transit' | 'Arrived at Port' | 'Customs' | 'Delivered', transportType: 'Sea' | 'Land' = 'Sea') => ({
  id, from: 'Shanghai', to: 'Cartagena', transportType, status, createdAt: '2026-08-29T10:30:00Z', deliveryTime: status === 'Delivered' ? 'Delivered' : '18 days',
})

export const catalogShowcase: Array<{ name: string; description: string; spec: Spec }> = [
  { name: 'AssistantMessage', description: 'Mensajes conversacionales con contenido anidado.', spec: { root: 'assistant', elements: { assistant: { type: 'AssistantMessage', props: { text: 'He encontrado tres envíos que necesitan atención.' }, children: [] } } } },
  ...(['Booking Confirmed', 'In Transit', 'Arrived at Port', 'Customs', 'Delivered'] as const).map((status) => ({ name: `ContainerProgress · ${status}`, description: 'Todas las etapas posibles del progreso de un contenedor.', spec: { root: `progress-${status}`, elements: { [`progress-${status}`]: { type: 'ContainerProgress', props: { currentStatus: status }, children: [] } } } })),
  ...(['Sea', 'Land'] as const).map((transportType) => ({ name: `DeliveryCard · ${transportType}`, description: 'Variantes de transporte marítimo y terrestre.', spec: { root: `delivery-${transportType}`, elements: { [`delivery-${transportType}`]: { type: 'DeliveryCard', props: delivery(`SHIP-${transportType}`, 'In Transit', transportType), children: [] } } } })),
  { name: 'DeliveryIssueCard', description: 'Tarjeta de entrega con incidencia operativa.', spec: { root: 'issue', elements: { issue: { type: 'DeliveryIssueCard', props: { ...delivery('SHIP-ISSUE', 'Customs'), issue: 'Customs clearance delayed' }, children: [] } } } },
  { name: 'OperationSummaryCard', description: 'Vista canónica de operación, ruta y contenedores obtenida del detalle 360°.', spec: { root: 'operation-summary', elements: { 'operation-summary': { type: 'OperationSummaryCard', props: { operationId: 'operation-1', referenceCode: 'MDS-DEMO-RED-081', clientName: 'Muebles del Sur S.A. de C.V.', status: 'CUSTOMS_CLEARANCE', tags: ['demo', 'customs-red'], notes: 'Active customs inspection case requiring a human decision.', containers: [{ id: 'container-1', containerNumber: 'MSDU7000810', status: 'CUSTOMS_HOLD', originPort: 'Ho Chi Minh City, Vietnam', destinationPort: 'Manzanillo, Mexico', eta: '2026-08-26T12:00:00Z', actualArrival: '2026-08-27T08:00:00Z', currentLocation: 'Aduana Manzanillo', currentVessel: 'MSC AURORA', customsLight: 'red' }] }, children: [] } } } },
  { name: 'OperationalAlertList', description: 'Alertas operativas normalizadas con severidad y estado de atención.', spec: { root: 'alerts', elements: { alerts: { type: 'OperationalAlertList', props: { title: 'Operational alerts', operationReference: 'MDS-DEMO-RED-081', alerts: [{ id: 'event-1', severity: 'critical', category: 'customs_light_assigned', title: 'Red customs light - physical inspection required', message: 'Container MSDU7000810 requires a supervisor response.', acknowledged: false, createdAt: '2026-08-29T23:14:48Z' }] }, children: [] } } } },
  { name: 'HumanDecisionCard', description: 'Decisión persistida que requiere aprobación humana; la mutación sigue fuera de este catálogo de lectura.', spec: { root: 'decision', elements: { decision: { type: 'HumanDecisionCard', props: { decisionId: 'decision-1', operationId: 'operation-1', title: 'Choose customs red-light response', description: 'Physical inspection may delay release.', question: 'How should Ari handle the red-light inspection?', severity: 'critical', executionMode: 'requires_approval', createdAt: '2026-08-29T23:14:48Z', options: [{ id: 'broker', label: 'Assign broker and expedite inspection' }, { id: 'client', label: 'Notify client and wait' }] }, children: [] } } } },
  { name: 'ShipmentDocumentsTimeline', description: 'Estados completed, in_progress, pending y missing.', spec: { root: 'documents', elements: { documents: { type: 'ShipmentDocumentsTimeline', props: { title: 'Shipment documents', subtitle: 'Document readiness by milestone', documents: [
    { id: 'purchase-order', title: 'Purchase order', description: 'Commercial order approved.', status: 'completed', date: '2026-08-21T12:00:00Z' },
    { id: 'booking-confirmation', title: 'Booking confirmation', description: 'Carrier space is confirmed.', status: 'in_progress', date: '2026-08-24T12:00:00Z' },
    { id: 'bill-of-lading', title: 'Bill of lading', description: 'Awaiting carrier upload.', status: 'pending' },
    { id: 'invoice', title: 'Commercial invoice', description: 'Required before customs review.', status: 'missing' },
  ] }, children: [] } } } },
  { name: 'DocumentDetailsCard', description: 'Detalle auditable de archivo, extracción, almacenamiento y partes relacionadas.', spec: { root: 'document-details', elements: { 'document-details': { type: 'DocumentDetailsCard', props: { documentId: 'document-1', type: 'BILL_OF_LADING', fileName: '03_Bill_of_Lading_MSCUBL7749201MX.pdf', reference: 'MSCUBL7749201MX', processingStatus: 'completed', confidence: 1, fileSizeBytes: 3337, mimeType: 'application/pdf', stored: true, createdAt: '2026-08-29T21:33:57Z', parties: [{ role: 'CARRIER', name: 'Mediterranean Shipping Company (MSC)' }, { role: 'CONSIGNEE', name: 'Muebles del Sur S.A. de C.V.', reference: 'MDS890512AB1' }] }, children: [] } } } },
  { name: 'CustomsClearancePanel', description: 'Semáforo aduanero, previo, pedimento y vínculos a alertas/decisiones.', spec: { root: 'customs', elements: { customs: { type: 'CustomsClearancePanel', props: { containerNumber: 'MSDU7000810', status: 'CUSTOMS_HOLD', customsLight: 'red', currentLocation: 'Aduana Manzanillo', actualArrival: '2026-08-27T08:00:00Z', previoStatus: 'pending', pedimentoStatus: 'pending', alertIds: ['event-1'], decisionIds: ['decision-1'] }, children: [] } } } },
  { name: 'EtaRiskCard', description: 'Deslizamiento medido entre ETA original y revisada, sin inventar exposición financiera.', spec: { root: 'eta-risk', elements: { 'eta-risk': { type: 'EtaRiskCard', props: { containerNumber: 'MSDU7000830', originalEta: '2026-09-04T18:00:00Z', currentEta: '2026-09-13T18:00:00Z', slipDays: 9, severity: 'critical', currentLocation: 'Busan, South Korea', currentVessel: 'MSC ORION' }, children: [] } } } },
  { name: 'AgentRunTimeline', description: 'Actividad persistida de agentes por paso, trigger y estado.', spec: { root: 'agent-runs', elements: { 'agent-runs': { type: 'AgentRunTimeline', props: { title: 'Agent activity', operationReference: 'MDS-DEMO-RED-081', runs: [{ id: 'run-1', agentName: 'ARI', flowStep: 'customs_red_light_escalation', status: 'waiting_input', triggerEvent: 'customs_light_assigned', tokensUsed: 0, createdAt: '2026-08-29T23:14:47Z', updatedAt: '2026-08-29T23:14:47Z' }] }, children: [] } } } },
  { name: 'ShipmentMilestoneTimeline', description: 'Historial de tránsito observado, presentado como ruta textual mientras no existan coordenadas.', spec: { root: 'milestones', elements: { milestones: { type: 'ShipmentMilestoneTimeline', props: { containerNumber: 'MSDU7000830', originPort: 'Cat Lai, Vietnam', destinationPort: 'Manzanillo, Mexico', milestones: [{ at: '2026-08-18T12:00:00Z', status: 'IN_TRANSIT', location: 'South China Sea' }, { at: '2026-08-25T06:00:00Z', status: 'AT_PORT', location: 'Busan, South Korea' }] }, children: [] } } } },
  { name: 'OperationsMetricsCard', description: 'Métricas operativas globales y distribución por estado con contrato restringido.', spec: { root: 'metrics', elements: { metrics: { type: 'OperationsMetricsCard', props: { totalOperations: 11, totalContainers: 11, containersInTransit: 4, containersInCustoms: 3, delayedContainersCount: 2, criticalAlertsCount: 4, pendingDecisionsCount: 4, byStatus: [{ status: 'CUSTOMS_CLEARANCE', count: 3 }, { status: 'DELIVERED', count: 1 }, { status: 'IN_TRANSIT', count: 4 }] }, children: [] } } } },
  { name: 'ReconciliationFindings', description: 'Comparación auditable entre BL, factura comercial y packing list.', spec: { root: 'reconciliation', elements: { reconciliation: { type: 'ReconciliationFindings', props: { status: 'discrepancy', severity: 'critical', discrepancies: [
    { field: 'containerNumber', severity: 'critical', values: { billOfLading: 'MSCU1234567', commercialInvoice: 'MSCU1234567', packingList: 'TGHU7654321' } },
    { field: 'weightKg', severity: 'warning', values: { billOfLading: 12000, commercialInvoice: 11950, packingList: 12000 } },
    { field: 'amountUsd', severity: 'warning', values: { billOfLading: 50000, commercialInvoice: 50000, packingList: 49800 } },
  ], evidenceIds: ['reconciliation-tool-result'] }, children: [] } } } },
  ...([['line', 'Gráficos de línea'], ['pie', 'Gráficos circulares'], ['scatter', 'Gráficos de dispersión'], ['stackedArea', 'Gráficos de áreas apiladas'], ['fluctuation', 'Gráficos de fluctuaciones'], ['spider', 'Gráficos de araña'], ['groupedBar', 'Gráficos de barras agrupadas'], ['pyramid', 'Gráficos de pirámide'], ['frequencyPolygon', 'Polígonos de frecuencia']] as const).map(([chartType, name], index) => ({ name, description: 'Diagrama estadístico registrado como componente JSON Render.', spec: { root: `catalog-chart-${index}`, elements: { [`catalog-chart-${index}`]: { type: 'CatalogChart', props: { title: name, description: 'Variante interactiva del catálogo', chartType, data: chartType === 'scatter' ? [{ label: 'A', x: 12, y: 24 }, { label: 'B', x: 25, y: 18 }, { label: 'C', x: 38, y: 42 }, { label: 'D', x: 52, y: 34 }, { label: 'E', x: 68, y: 58 }] : chartType === 'pie' ? [{ label: 'Entregados', value: 46 }, { label: 'En tránsito', value: 31 }, { label: 'Aduana', value: 14 }, { label: 'Retrasados', value: 9 }] : chartType === 'spider' ? [{ label: 'Velocidad', value: 82 }, { label: 'Coste', value: 68 }, { label: 'Calidad', value: 91 }, { label: 'Cobertura', value: 74 }, { label: 'Riesgo', value: 60 }] : [{ label: 'Lun', value: 24, value2: 15 }, { label: 'Mar', value: 38, value2: 22 }, { label: 'Mié', value: 31, value2: 28 }, { label: 'Jue', value: 46, value2: 25 }, { label: 'Vie', value: 42, value2: 34 }], height: 260, showGrid: true }, children: [] } } } })),
  ...([['vertical', true, true], ['horizontal', true, false], ['vertical', false, true], ['horizontal', false, false]] as const).map(([orientation, showValues, showGrid], index) => ({ name: `BarChart · ${orientation} · ${showValues ? 'values' : 'clean'}`, description: 'Variantes de orientación, valores y cuadrícula.', spec: { root: `chart-${index}`, elements: { [`chart-${index}`]: { type: 'BarChart', props: { title: 'Shipments by status', description: 'Current shipment distribution', data: [{ label: 'Delivered', value: 42 }, { label: 'In transit', value: 28 }, { label: 'Customs', value: 9 }, { label: 'Delayed', value: 6 }], orientation, showValues, showGrid, height: orientation === 'horizontal' ? 260 : 300 }, children: [] } } } })),
]
