export type Locale = 'es' | 'en' | 'pt'

export const localeLabels: Record<Locale, string> = { es: 'Español', en: 'English', pt: 'Português' }

const translations = {
  es: { summary: 'Resumen', runs: 'Runs', fleet: 'Flota', calendar: 'Calendario', issues: 'Incidencias', map: 'Mapa', analytics: 'Analíticas', news: 'Noticias', settings: 'Ajustes', help: 'Ayuda', chat: 'Chat', operations: 'Operaciones', workspace: 'Workspace', goodMorning: 'Buenos días, Alex', search: 'Buscar runs, rutas...', chatTeam: 'Chat del equipo', dateLocale: 'es-MX', activeRuns: 'Runs activos', eta: 'ETA medio', costKm: 'Coste / km', networkHealth: 'Salud de la red', excellent: 'Excelente', review: 'Revisar decisiones', allControl: 'Todo bajo control.', operationalSummary: 'Resumen operativo', networkCapacity: 'Tu red está funcionando al', decisionsAttention: 'Hay 3 decisiones que requieren tu atención.', performance: 'Rendimiento', runActivity: 'Actividad de runs', thisWeek: 'Esta semana', finances: 'Finanzas', operatingCost: 'Coste operativo', thisMonth: 'este mes', monthlyBudget: 'Presupuesto mensual', tracking: 'Seguimiento', recentRuns: 'Runs recientes', seeAll: 'Ver todos', seeLess: 'Ver menos', planning: 'Planificación', nextDepartures: 'Próximas salidas', fullCalendar: 'Ver calendario completo', newAction: 'Nueva acción', intelligence: 'Inteligencia operativa', analyticsDescription: 'Convierte el movimiento de tu red en decisiones más claras y rápidas.', exportReport: 'Exportar informe', onTimeDelivery: 'Entrega a tiempo', distanceTraveled: 'Km recorridos', averageRunCost: 'Coste medio / run', resolvedIssues: 'Incidencias resueltas', operationalVolume: 'Volumen de operaciones', completedRuns: 'Runs completados', networkHealthSection: 'Salud de red', globalEfficiency: 'Eficiencia global', chatPlaceholder: 'Escribe un mensaje para Ari...', language: 'Idioma', administrator: 'Administrador', principalWorkspace: 'Workspace principal' },
  en: { summary: 'Overview', runs: 'Runs', fleet: 'Fleet', calendar: 'Calendar', issues: 'Issues', map: 'Map', analytics: 'Analytics', news: 'News', settings: 'Settings', help: 'Help', chat: 'Chat', operations: 'Operations', workspace: 'Workspace', goodMorning: 'Good morning, Alex', search: 'Search runs, routes...', chatTeam: 'Team chat', dateLocale: 'en-US', activeRuns: 'Active runs', eta: 'Average ETA', costKm: 'Cost / km', networkHealth: 'Network health', excellent: 'Excellent', review: 'Review decisions', allControl: 'Everything under control.', operationalSummary: 'Operational summary', networkCapacity: 'Your network is operating at', decisionsAttention: 'There are 3 decisions requiring your attention.', performance: 'Performance', runActivity: 'Run activity', thisWeek: 'This week', finances: 'Finance', operatingCost: 'Operating cost', thisMonth: 'this month', monthlyBudget: 'Monthly budget', tracking: 'Tracking', recentRuns: 'Recent runs', seeAll: 'See all', seeLess: 'See less', planning: 'Planning', nextDepartures: 'Upcoming departures', fullCalendar: 'View full calendar', newAction: 'New action', intelligence: 'Operational intelligence', analyticsDescription: 'Turn network movement into clearer, faster decisions.', exportReport: 'Export report', onTimeDelivery: 'On-time delivery', distanceTraveled: 'Distance traveled', averageRunCost: 'Average run cost', resolvedIssues: 'Issues resolved', operationalVolume: 'Operations volume', completedRuns: 'Completed runs', networkHealthSection: 'Network health', globalEfficiency: 'Global efficiency', chatPlaceholder: 'Write a message for Ari...', language: 'Language', administrator: 'Administrator', principalWorkspace: 'Primary workspace' },
  pt: { summary: 'Resumo', runs: 'Runs', fleet: 'Frota', calendar: 'Calendário', issues: 'Incidentes', map: 'Mapa', analytics: 'Análises', news: 'Notícias', settings: 'Configurações', help: 'Ajuda', chat: 'Chat', operations: 'Operações', workspace: 'Workspace', goodMorning: 'Bom dia, Alex', search: 'Buscar runs, rotas...', chatTeam: 'Chat da equipe', dateLocale: 'pt-BR', activeRuns: 'Runs ativos', eta: 'ETA médio', costKm: 'Custo / km', networkHealth: 'Saúde da rede', excellent: 'Excelente', review: 'Revisar decisões', allControl: 'Tudo sob controle.', operationalSummary: 'Resumo operacional', networkCapacity: 'Sua rede está operando a', decisionsAttention: 'Há 3 decisões que exigem sua atenção.', performance: 'Desempenho', runActivity: 'Atividade dos runs', thisWeek: 'Esta semana', finances: 'Finanças', operatingCost: 'Custo operacional', thisMonth: 'este mês', monthlyBudget: 'Orçamento mensal', tracking: 'Acompanhamento', recentRuns: 'Runs recentes', seeAll: 'Ver todos', seeLess: 'Ver menos', planning: 'Planejamento', nextDepartures: 'Próximas saídas', fullCalendar: 'Ver calendário completo', newAction: 'Nova ação', intelligence: 'Inteligência operacional', analyticsDescription: 'Transforme o movimento da sua rede em decisões mais claras e rápidas.', exportReport: 'Exportar relatório', onTimeDelivery: 'Entrega no prazo', distanceTraveled: 'Km percorridos', averageRunCost: 'Custo médio / run', resolvedIssues: 'Incidentes resolvidos', operationalVolume: 'Volume de operações', completedRuns: 'Runs concluídos', networkHealthSection: 'Saúde da rede', globalEfficiency: 'Eficiência global', chatPlaceholder: 'Escreva uma mensagem para Ari...', language: 'Idioma', administrator: 'Administrador', principalWorkspace: 'Workspace principal' },
} as const

export type TranslationKey = keyof typeof translations.es
export function getTranslations(locale: Locale) { return translations[locale] }
